// Banco de perguntas do jogo. Vive no backend (a "inteligência" do jogo)
// para que o gabarito nunca seja enviado aos clientes antes da resposta.
const QUESTIONS_DB = {
    facil: [
        { categoria: "matematica", texto: "Quanto é 7 x 8?", opcoes: ["54", "56", "58", "64"], correta: 1 },
        { categoria: "matematica", texto: "Qual é a raiz quadrada de 144?", opcoes: ["10", "11", "12", "14"], correta: 2 },
        { categoria: "matematica", texto: "Quanto é 15 + 27?", opcoes: ["40", "42", "43", "52"], correta: 1 },
        { categoria: "matematica", texto: "Qual é o resultado de 100 ÷ 4?", opcoes: ["20", "25", "30", "50"], correta: 1 },
        { categoria: "matematica", texto: "Quanto é 9²?", opcoes: ["18", "72", "81", "91"], correta: 2 },
        { categoria: "matematica", texto: "Qual é o dobro de 35?", opcoes: ["60", "65", "70", "75"], correta: 2 },
        { categoria: "matematica", texto: "Quanto é 3 x 3 x 3?", opcoes: ["9", "18", "27", "36"], correta: 2 },
        { categoria: "matematica", texto: "Qual número é primo?", opcoes: ["4", "9", "11", "15"], correta: 2 },

        { categoria: "biologia", texto: "Qual é o maior órgão do corpo humano?", opcoes: ["Fígado", "Pulmão", "Pele", "Coração"], correta: 2 },
        { categoria: "biologia", texto: "Quantos ossos tem o corpo humano adulto?", opcoes: ["186", "206", "226", "256"], correta: 1 },
        { categoria: "biologia", texto: "Qual gás as plantas absorvem na fotossíntese?", opcoes: ["Oxigênio", "Nitrogênio", "Gás carbônico", "Hidrogênio"], correta: 2 },
        { categoria: "biologia", texto: "Qual a célula responsável pela defesa do corpo?", opcoes: ["Hemácia", "Leucócito", "Plaqueta", "Neurônio"], correta: 1 },
        { categoria: "biologia", texto: "O que as mitocôndrias produzem?", opcoes: ["Proteínas", "Energia (ATP)", "DNA", "Lipídios"], correta: 1 },
        { categoria: "biologia", texto: "Qual é a unidade básica da vida?", opcoes: ["Átomo", "Molécula", "Célula", "Tecido"], correta: 2 },
        { categoria: "biologia", texto: "Qual animal é um mamífero?", opcoes: ["Tubarão", "Golfinho", "Crocodilo", "Tartaruga"], correta: 1 },
        { categoria: "biologia", texto: "Qual vitamina é produzida pela exposição ao sol?", opcoes: ["Vitamina A", "Vitamina B", "Vitamina C", "Vitamina D"], correta: 3 },

        { categoria: "geografia", texto: "Qual é o maior continente do mundo?", opcoes: ["África", "América", "Ásia", "Europa"], correta: 2 },
        { categoria: "geografia", texto: "Qual é o rio mais longo do mundo?", opcoes: ["Amazonas", "Nilo", "Mississipi", "Yangtzé"], correta: 1 },
        { categoria: "geografia", texto: "Qual é o país mais populoso do mundo?", opcoes: ["Estados Unidos", "Índia", "China", "Indonésia"], correta: 1 },
        { categoria: "geografia", texto: "Quantos estados tem o Brasil?", opcoes: ["24", "25", "26", "27"], correta: 2 },
        { categoria: "geografia", texto: "Qual é o maior oceano do mundo?", opcoes: ["Atlântico", "Índico", "Pacífico", "Ártico"], correta: 2 },
        { categoria: "geografia", texto: "Qual é a capital do Japão?", opcoes: ["Pequim", "Seul", "Bangkok", "Tóquio"], correta: 3 },
        { categoria: "geografia", texto: "Em que continente fica o Egito?", opcoes: ["Ásia", "África", "Europa", "Oceania"], correta: 1 },
        { categoria: "geografia", texto: "Qual é o menor país do mundo?", opcoes: ["Mônaco", "Vaticano", "Malta", "Liechtenstein"], correta: 1 },

        { categoria: "historia", texto: "Em que ano o Brasil foi descoberto?", opcoes: ["1400", "1450", "1500", "1550"], correta: 2 },
        { categoria: "historia", texto: "Quem proclamou a independência do Brasil?", opcoes: ["Tiradentes", "Dom Pedro I", "Dom Pedro II", "Getúlio Vargas"], correta: 1 },
        { categoria: "historia", texto: "Em que ano o homem pisou na Lua pela primeira vez?", opcoes: ["1965", "1967", "1969", "1971"], correta: 2 },
        { categoria: "historia", texto: "Qual civilização construiu as pirâmides de Gizé?", opcoes: ["Romana", "Grega", "Egípcia", "Persa"], correta: 2 },
        { categoria: "historia", texto: "Quem pintou a Mona Lisa?", opcoes: ["Michelangelo", "Leonardo da Vinci", "Rafael", "Donatello"], correta: 1 },
        { categoria: "historia", texto: "Em que ano começou a Primeira Guerra Mundial?", opcoes: ["1912", "1914", "1916", "1918"], correta: 1 },
        { categoria: "historia", texto: "Qual era o nome do navio que afundou em 1912?", opcoes: ["Queen Mary", "Titanic", "Britannic", "Lusitania"], correta: 1 },
        { categoria: "historia", texto: "Quem foi o primeiro presidente do Brasil?", opcoes: ["Dom Pedro I", "Deodoro da Fonseca", "Getúlio Vargas", "Prudente de Morais"], correta: 1 },

        { categoria: "fisica", texto: "Qual é a velocidade da luz (aproximada)?", opcoes: ["100.000 km/s", "200.000 km/s", "300.000 km/s", "400.000 km/s"], correta: 2 },
        { categoria: "fisica", texto: "Qual é a unidade de medida de força?", opcoes: ["Watt", "Joule", "Newton", "Pascal"], correta: 2 },
        { categoria: "fisica", texto: "O que mede um termômetro?", opcoes: ["Pressão", "Velocidade", "Temperatura", "Massa"], correta: 2 },
        { categoria: "fisica", texto: "Qual planeta está mais perto do Sol?", opcoes: ["Vênus", "Mercúrio", "Marte", "Terra"], correta: 1 },
        { categoria: "fisica", texto: "O som se propaga mais rápido em qual meio?", opcoes: ["Vácuo", "Ar", "Água", "Aço"], correta: 3 },
        { categoria: "fisica", texto: "Quem formulou a Lei da Gravitação Universal?", opcoes: ["Einstein", "Newton", "Galileu", "Kepler"], correta: 1 },
        { categoria: "fisica", texto: "Qual é a unidade de medida de energia?", opcoes: ["Newton", "Joule", "Watt", "Ampere"], correta: 1 },
        { categoria: "fisica", texto: "Quantos planetas tem o Sistema Solar?", opcoes: ["7", "8", "9", "10"], correta: 1 },

        { categoria: "computacao", texto: "O que significa HTML?", opcoes: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyper Transfer Mode Link", "Home Tool Markup Language"], correta: 0 },
        { categoria: "computacao", texto: "Qual é o sistema de numeração usado por computadores?", opcoes: ["Decimal", "Binário", "Octal", "Hexadecimal"], correta: 1 },
        { categoria: "computacao", texto: "O que é um bug em programação?", opcoes: ["Um vírus", "Um erro no código", "Um tipo de dado", "Um hardware"], correta: 1 },
        { categoria: "computacao", texto: "O que significa CPU?", opcoes: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Power Unit"], correta: 0 },
        { categoria: "computacao", texto: "Qual linguagem é mais usada para estilizar páginas web?", opcoes: ["JavaScript", "Python", "CSS", "Java"], correta: 2 },
        { categoria: "computacao", texto: "O que é RAM?", opcoes: ["Memória permanente", "Memória volátil", "Disco rígido", "Processador"], correta: 1 },
        { categoria: "computacao", texto: "Quantos bits tem 1 byte?", opcoes: ["4", "8", "16", "32"], correta: 1 },
        { categoria: "computacao", texto: "Qual empresa criou o Windows?", opcoes: ["Apple", "Google", "Microsoft", "IBM"], correta: 2 }
    ],

    medio: [
        { categoria: "matematica", texto: "Qual é o valor de π (pi) com duas casas decimais?", opcoes: ["3.12", "3.14", "3.16", "3.18"], correta: 1 },
        { categoria: "matematica", texto: "Qual é o resultado de log₁₀(1000)?", opcoes: ["2", "3", "4", "10"], correta: 1 },
        { categoria: "matematica", texto: "Em um triângulo retângulo com catetos 3 e 4, qual a hipotenusa?", opcoes: ["5", "6", "7", "8"], correta: 0 },
        { categoria: "matematica", texto: "Quanto é 2⁵?", opcoes: ["16", "32", "64", "128"], correta: 1 },
        { categoria: "matematica", texto: "Qual é a soma dos ângulos internos de um triângulo?", opcoes: ["90°", "180°", "270°", "360°"], correta: 1 },
        { categoria: "matematica", texto: "Quanto é a fatorial de 5 (5!)?", opcoes: ["60", "100", "120", "150"], correta: 2 },
        { categoria: "matematica", texto: "Qual é o MMC de 12 e 18?", opcoes: ["24", "36", "48", "72"], correta: 1 },
        { categoria: "matematica", texto: "Se f(x) = 2x + 3, qual é f(4)?", opcoes: ["8", "10", "11", "14"], correta: 2 },

        { categoria: "biologia", texto: "Qual é o nome do processo de divisão celular que gera células iguais?", opcoes: ["Meiose", "Mitose", "Fissão", "Fusão"], correta: 1 },
        { categoria: "biologia", texto: "Qual é a molécula que carrega a informação genética?", opcoes: ["RNA", "ATP", "DNA", "Proteína"], correta: 2 },
        { categoria: "biologia", texto: "Em que organela ocorre a fotossíntese?", opcoes: ["Mitocôndria", "Ribossomo", "Cloroplasto", "Lisossomo"], correta: 2 },
        { categoria: "biologia", texto: "Quantos cromossomos tem uma célula humana normal?", opcoes: ["23", "44", "46", "48"], correta: 2 },
        { categoria: "biologia", texto: "Qual tipo sanguíneo é considerado doador universal?", opcoes: ["A+", "B+", "AB+", "O-"], correta: 3 },
        { categoria: "biologia", texto: "Qual é a função dos ribossomos?", opcoes: ["Digestão celular", "Síntese de proteínas", "Produção de energia", "Transporte de substâncias"], correta: 1 },
        { categoria: "biologia", texto: "Qual é o maior bioma brasileiro?", opcoes: ["Cerrado", "Amazônia", "Mata Atlântica", "Caatinga"], correta: 1 },
        { categoria: "biologia", texto: "O que é homeostase?", opcoes: ["Reprodução celular", "Equilíbrio interno do organismo", "Mutação genética", "Evolução das espécies"], correta: 1 },

        { categoria: "geografia", texto: "Qual é a montanha mais alta do mundo?", opcoes: ["K2", "Monte Everest", "Kangchenjunga", "Monte Blanc"], correta: 1 },
        { categoria: "geografia", texto: "Qual linha imaginária divide a Terra em Norte e Sul?", opcoes: ["Trópico de Capricórnio", "Meridiano de Greenwich", "Linha do Equador", "Trópico de Câncer"], correta: 2 },
        { categoria: "geografia", texto: "Qual país tem a maior extensão territorial?", opcoes: ["Canadá", "China", "Estados Unidos", "Rússia"], correta: 3 },
        { categoria: "geografia", texto: "Qual é o deserto mais quente do mundo?", opcoes: ["Gobi", "Saara", "Atacama", "Kalahari"], correta: 1 },
        { categoria: "geografia", texto: "Quantos fusos horários tem o Brasil?", opcoes: ["3", "4", "5", "6"], correta: 1 },
        { categoria: "geografia", texto: "Qual rio corta a cidade de São Paulo?", opcoes: ["Rio Paraná", "Rio Tietê", "Rio São Francisco", "Rio Amazonas"], correta: 1 },
        { categoria: "geografia", texto: "Qual é a capital da Austrália?", opcoes: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correta: 2 },
        { categoria: "geografia", texto: "Em que continente fica a Cordilheira dos Andes?", opcoes: ["América do Norte", "América do Sul", "Ásia", "Europa"], correta: 1 },

        { categoria: "historia", texto: "Em que ano aconteceu a Revolução Francesa?", opcoes: ["1776", "1789", "1799", "1815"], correta: 1 },
        { categoria: "historia", texto: "Quem foi o líder da Alemanha na Segunda Guerra Mundial?", opcoes: ["Mussolini", "Stalin", "Hitler", "Churchill"], correta: 2 },
        { categoria: "historia", texto: "Qual tratado encerrou a Primeira Guerra Mundial?", opcoes: ["Versalhes", "Westfália", "Tordesilhas", "Utrecht"], correta: 0 },
        { categoria: "historia", texto: "Em que ano foi abolida a escravidão no Brasil?", opcoes: ["1822", "1850", "1888", "1891"], correta: 2 },
        { categoria: "historia", texto: "Quem descobriu o Brasil oficialmente?", opcoes: ["Cristóvão Colombo", "Vasco da Gama", "Pedro Álvares Cabral", "Fernão de Magalhães"], correta: 2 },
        { categoria: "historia", texto: "Qual império dominou o Mediterrâneo na Antiguidade?", opcoes: ["Grego", "Romano", "Persa", "Egípcio"], correta: 1 },
        { categoria: "historia", texto: "Em que ano o Muro de Berlim caiu?", opcoes: ["1985", "1987", "1989", "1991"], correta: 2 },
        { categoria: "historia", texto: "Qual foi a última monarquia no Brasil?", opcoes: ["Dom Pedro I", "Dom João VI", "Dom Pedro II", "Princesa Isabel"], correta: 2 },

        { categoria: "fisica", texto: "Qual é a fórmula da segunda lei de Newton?", opcoes: ["F = m·v", "F = m·a", "F = m·g", "F = m/a"], correta: 1 },
        { categoria: "fisica", texto: "O que é um elétron?", opcoes: ["Partícula com carga positiva", "Partícula com carga negativa", "Partícula neutra", "Partícula de luz"], correta: 1 },
        { categoria: "fisica", texto: "Qual é a unidade de medida de potência?", opcoes: ["Joule", "Newton", "Watt", "Volt"], correta: 2 },
        { categoria: "fisica", texto: "O que acontece com a água a 100°C ao nível do mar?", opcoes: ["Congela", "Evapora", "Sublima", "Condensa"], correta: 1 },
        { categoria: "fisica", texto: "Qual é a aceleração da gravidade na Terra (aproximada)?", opcoes: ["8.8 m/s²", "9.8 m/s²", "10.8 m/s²", "11.8 m/s²"], correta: 1 },
        { categoria: "fisica", texto: "Qual tipo de onda é o som?", opcoes: ["Eletromagnética", "Mecânica", "Nuclear", "Gravitacional"], correta: 1 },
        { categoria: "fisica", texto: "O que é inércia?", opcoes: ["Tendência de manter o estado de movimento", "Força de atrito", "Energia armazenada", "Velocidade constante"], correta: 0 },
        { categoria: "fisica", texto: "Qual a cor de luz com maior comprimento de onda?", opcoes: ["Azul", "Verde", "Amarelo", "Vermelho"], correta: 3 },

        { categoria: "computacao", texto: "O que é um algoritmo?", opcoes: ["Um tipo de vírus", "Uma sequência de passos para resolver um problema", "Uma linguagem de programação", "Um tipo de hardware"], correta: 1 },
        { categoria: "computacao", texto: "Qual estrutura de dados segue a regra FIFO?", opcoes: ["Pilha", "Fila", "Árvore", "Grafo"], correta: 1 },
        { categoria: "computacao", texto: "O que significa HTTP?", opcoes: ["HyperText Transfer Protocol", "High Tech Transfer Program", "Hyper Terminal Transfer Path", "Home Text Transfer Protocol"], correta: 0 },
        { categoria: "computacao", texto: "Qual é a complexidade do algoritmo de busca binária?", opcoes: ["O(n)", "O(n²)", "O(log n)", "O(1)"], correta: 2 },
        { categoria: "computacao", texto: "O que é uma variável em programação?", opcoes: ["Um tipo de loop", "Um espaço na memória que armazena dados", "Uma função", "Um operador"], correta: 1 },
        { categoria: "computacao", texto: "Qual destes é um sistema operacional?", opcoes: ["Python", "Chrome", "Linux", "MySQL"], correta: 2 },
        { categoria: "computacao", texto: "O que faz o comando 'git commit'?", opcoes: ["Envia código para o servidor", "Salva alterações no repositório local", "Baixa código do servidor", "Apaga alterações"], correta: 1 },
        { categoria: "computacao", texto: "O que é uma API?", opcoes: ["Um banco de dados", "Uma interface de programação de aplicações", "Um servidor web", "Um protocolo de rede"], correta: 1 }
    ],

    dificil: [
        { categoria: "matematica", texto: "Qual é a derivada de x³?", opcoes: ["x²", "2x²", "3x²", "3x³"], correta: 2 },
        { categoria: "matematica", texto: "Qual é o valor de sen(90°)?", opcoes: ["0", "0.5", "1", "-1"], correta: 2 },
        { categoria: "matematica", texto: "Quantos lados tem um dodecaedro regular?", opcoes: ["10", "12", "14", "20"], correta: 1 },
        { categoria: "matematica", texto: "Qual é a integral de 2x dx?", opcoes: ["x²", "x² + C", "2x² + C", "x + C"], correta: 1 },
        { categoria: "matematica", texto: "Qual é o determinante da matriz [[1,2],[3,4]]?", opcoes: ["-2", "2", "-10", "10"], correta: 0 },
        { categoria: "matematica", texto: "Em uma PA com a1=3 e razão 5, qual é o 10º termo?", opcoes: ["48", "50", "53", "55"], correta: 0 },
        { categoria: "matematica", texto: "Qual é o limite de (1 + 1/n)^n quando n→∞?", opcoes: ["1", "π", "e", "∞"], correta: 2 },
        { categoria: "matematica", texto: "Quantas combinações de 5 elementos tomados 2 a 2?", opcoes: ["5", "10", "15", "20"], correta: 1 },

        { categoria: "biologia", texto: "Qual enzima inicia a digestão de amido na boca?", opcoes: ["Pepsina", "Amilase salivar", "Lipase", "Tripsina"], correta: 1 },
        { categoria: "biologia", texto: "Qual é a fase da meiose em que ocorre o crossing-over?", opcoes: ["Prófase I", "Metáfase I", "Anáfase II", "Telófase II"], correta: 0 },
        { categoria: "biologia", texto: "O que é o ciclo de Krebs?", opcoes: ["Replicação do DNA", "Ciclo de produção de energia celular", "Divisão celular", "Transcrição do RNA"], correta: 1 },
        { categoria: "biologia", texto: "Qual é a função do complexo de Golgi?", opcoes: ["Produzir energia", "Modificar e empacotar proteínas", "Sintetizar DNA", "Realizar fotossíntese"], correta: 1 },
        { categoria: "biologia", texto: "O que é um alelo dominante?", opcoes: ["Que só aparece em homozigose", "Que se manifesta mesmo em heterozigose", "Que causa mutações", "Que é mais raro na população"], correta: 1 },
        { categoria: "biologia", texto: "Qual é a relação ecológica entre o tubarão e a rêmora?", opcoes: ["Parasitismo", "Comensalismo", "Mutualismo", "Predação"], correta: 1 },
        { categoria: "biologia", texto: "O que é a cadeia de transporte de elétrons?", opcoes: ["Parte da replicação do DNA", "Etapa final da respiração celular", "Fase da fotossíntese", "Tipo de divisão celular"], correta: 1 },
        { categoria: "biologia", texto: "Qual hormônio regula o nível de glicose no sangue?", opcoes: ["Adrenalina", "Insulina", "Tiroxina", "Cortisol"], correta: 1 },

        { categoria: "geografia", texto: "Qual é o ponto mais profundo dos oceanos?", opcoes: ["Fossa de Porto Rico", "Fossa das Marianas", "Fossa de Java", "Fossa de Tonga"], correta: 1 },
        { categoria: "geografia", texto: "Qual país possui a maior reserva de água doce do mundo?", opcoes: ["Canadá", "Rússia", "Brasil", "China"], correta: 2 },
        { categoria: "geografia", texto: "O que são placas tectônicas?", opcoes: ["Camadas da atmosfera", "Grandes blocos da litosfera", "Correntes oceânicas", "Faixas de vegetação"], correta: 1 },
        { categoria: "geografia", texto: "Qual é o fenômeno climático El Niño?", opcoes: ["Resfriamento do Pacífico", "Aquecimento do Pacífico equatorial", "Aumento da camada de ozônio", "Inversão dos ventos alísios"], correta: 1 },
        { categoria: "geografia", texto: "Qual é a capital do Cazaquistão?", opcoes: ["Almaty", "Astana", "Bishkek", "Tashkent"], correta: 1 },
        { categoria: "geografia", texto: "Qual tipo de rocha é formada por resfriamento de magma?", opcoes: ["Sedimentar", "Metamórfica", "Ígnea", "Calcária"], correta: 2 },
        { categoria: "geografia", texto: "O que é a Corrente do Golfo?", opcoes: ["Corrente de ar frio", "Corrente marítima quente do Atlântico", "Fenômeno vulcânico", "Tipo de maré"], correta: 1 },
        { categoria: "geografia", texto: "Qual é a escala usada para medir terremotos?", opcoes: ["Beaufort", "Richter", "Celsius", "Mohs"], correta: 1 },

        { categoria: "historia", texto: "Qual foi o estopim da Primeira Guerra Mundial?", opcoes: ["Invasão da Polônia", "Assassinato do Arquiduque Franz Ferdinand", "Bombardeio de Pearl Harbor", "Revolução Russa"], correta: 1 },
        { categoria: "historia", texto: "Qual civilização inventou a escrita cuneiforme?", opcoes: ["Egípcia", "Grega", "Suméria", "Chinesa"], correta: 2 },
        { categoria: "historia", texto: "O que foi a Guerra Fria?", opcoes: ["Guerra entre EUA e URSS com combate direto", "Conflito ideológico sem confronto militar direto", "Guerra no Ártico", "Conflito na Sibéria"], correta: 1 },
        { categoria: "historia", texto: "Em que período histórico ocorreu o Renascimento?", opcoes: ["Idade Média", "Idade Moderna", "Idade Contemporânea", "Antiguidade"], correta: 1 },
        { categoria: "historia", texto: "Qual foi a consequência do Tratado de Tordesilhas?", opcoes: ["Fim da escravidão", "Divisão de terras entre Portugal e Espanha", "Independência das colônias", "Criação da ONU"], correta: 1 },
        { categoria: "historia", texto: "Quem liderou a Revolução Cubana?", opcoes: ["Hugo Chávez", "Che Guevara e Fidel Castro", "Simon Bolívar", "Salvador Allende"], correta: 1 },
        { categoria: "historia", texto: "O que foi a Inquisição?", opcoes: ["Tribunal religioso que julgava heresias", "Parlamento medieval", "Ordem de cavaleiros", "Sistema de comércio"], correta: 0 },
        { categoria: "historia", texto: "Qual imperador romano legalizou o cristianismo?", opcoes: ["Nero", "Augusto", "Constantino", "Júlio César"], correta: 2 },

        { categoria: "fisica", texto: "O que é o efeito Doppler?", opcoes: ["Mudança na frequência de ondas devido ao movimento", "Reflexão total da luz", "Difração de ondas", "Polarização da luz"], correta: 0 },
        { categoria: "fisica", texto: "Qual é a equação de Einstein para equivalência massa-energia?", opcoes: ["E = mc", "E = mc²", "E = m/c²", "E = m²c"], correta: 1 },
        { categoria: "fisica", texto: "O que são quarks?", opcoes: ["Partículas subatômicas que formam prótons e nêutrons", "Tipos de átomos", "Ondas eletromagnéticas", "Elementos químicos"], correta: 0 },
        { categoria: "fisica", texto: "Qual é o princípio da incerteza de Heisenberg?", opcoes: ["Não se pode medir posição e momento simultaneamente com precisão", "A energia se conserva", "Toda ação tem reação", "A luz é onda e partícula"], correta: 0 },
        { categoria: "fisica", texto: "O que é supercondutividade?", opcoes: ["Condução de calor extrema", "Resistência elétrica zero a baixas temperaturas", "Velocidade acima da luz", "Estado plasmático da matéria"], correta: 1 },
        { categoria: "fisica", texto: "Qual é a terceira lei de Newton?", opcoes: ["F = ma", "Ação e reação", "Lei da inércia", "Lei da gravitação"], correta: 1 },
        { categoria: "fisica", texto: "O que é a constante de Planck?", opcoes: ["Velocidade da luz", "Constante que relaciona energia e frequência", "Carga do elétron", "Número de Avogadro"], correta: 1 },
        { categoria: "fisica", texto: "Qual fenômeno explica por que o céu é azul?", opcoes: ["Refração", "Espalhamento de Rayleigh", "Reflexão total", "Difração"], correta: 1 },

        { categoria: "computacao", texto: "O que é recursão em programação?", opcoes: ["Um loop infinito", "Uma função que chama a si mesma", "Um tipo de variável", "Um padrão de design"], correta: 1 },
        { categoria: "computacao", texto: "Qual é a diferença entre TCP e UDP?", opcoes: ["TCP é confiável, UDP não garante entrega", "UDP é mais lento", "TCP é wireless", "Não há diferença"], correta: 0 },
        { categoria: "computacao", texto: "O que é um deadlock?", opcoes: ["Erro de sintaxe", "Situação onde processos ficam bloqueados mutuamente", "Tipo de malware", "Falha de hardware"], correta: 1 },
        { categoria: "computacao", texto: "O que é polimorfismo em POO?", opcoes: ["Criar múltiplas classes", "Capacidade de um objeto assumir várias formas", "Herança múltipla", "Encapsulamento"], correta: 1 },
        { categoria: "computacao", texto: "Qual é a notação Big O do algoritmo Bubble Sort?", opcoes: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], correta: 2 },
        { categoria: "computacao", texto: "O que é normalização em banco de dados?", opcoes: ["Criptografar dados", "Organizar dados para reduzir redundância", "Fazer backup", "Indexar tabelas"], correta: 1 },
        { categoria: "computacao", texto: "O que é o padrão de projeto Singleton?", opcoes: ["Classe com apenas uma instância", "Classe sem métodos", "Interface para múltiplas classes", "Padrão de herança"], correta: 0 },
        { categoria: "computacao", texto: "O que é uma árvore binária de busca?", opcoes: ["Estrutura linear", "Estrutura onde nó esquerdo < pai < nó direito", "Grafo sem ciclos", "Lista duplamente encadeada"], correta: 1 }
    ]
};

module.exports = { QUESTIONS_DB };
